name: Build release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-18.04
    env:
      RELEASE_OS: linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Build
        run: |
          docker run --rm -v `pwd`:/io \
          -e RELEASE_OS=$RELEASE_OS \
          -e RELEASE_VERSION=$RELEASE_VERSION \
          phusion/holy-build-box-64:latest /hbb_exe/activate-exec \
          bash -x -c "cd io && make build_$RELEASE_OS && make compile_release_$RELEASE_OS"
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/bustools_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          asset_name: bustools_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          tag: ${{ github.ref }}

  build-mac:
    name: Build mac
    runs-on: macos-latest
    env:
      RELEASE_OS: mac
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Build
        run: make build_$RELEASE_OS && make compile_release_$RELEASE_OS
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/bustools_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          asset_name: bustools_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          tag: ${{ github.ref }}

  # build-windows:
  #
  # build-macos:
  #
  # release-to-pypi:
  #   name: Release to Pypi
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@master
  #     - name: Setup python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: '3.7'
  #         architecture: x64
  #     - name: Install dependencies
  #       run: pip install -r dev-requirements.txt
  #     - name: Build
  #       run: python setup.py sdist bdist_wheel
  #     - name: Upload
  #       run: twine upload dist/*
  #       env:
  #         TWINE_REPOSITORY_URL: ${{ secrets.PYPI_URL }}
  #         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  #         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
