name: Build release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-18.04
    env:
      RELEASE_OS: linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Build
        run: docker run --rm -v `pwd`:/io -e RELEASE_OS=$RELEASE_OS -e RELEASE_VERSION=$RELEASE_VERSION -e CC='ccache gcc' -e CXX='ccache g++' -e CCACHE_DIR='/io/cache' phusion/holy-build-box-64:latest bash -c "source /hbb_exe/activate && cd io && make build_linux && make compile_release"
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/bustools_linux-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          asset_name: bustools_linux-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          tag: ${{ github.ref }}


  # build-windows:
  #
  # build-macos:
  #
  # release-to-pypi:
  #   name: Release to Pypi
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@master
  #     - name: Setup python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: '3.7'
  #         architecture: x64
  #     - name: Install dependencies
  #       run: pip install -r dev-requirements.txt
  #     - name: Build
  #       run: python setup.py sdist bdist_wheel
  #     - name: Upload
  #       run: twine upload dist/*
  #       env:
  #         TWINE_REPOSITORY_URL: ${{ secrets.PYPI_URL }}
  #         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  #         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
